### ISSUE TITLE
idk how to download stuff on githubbbb helppppppp

### ISSUE THREAD

**Issue by Hecate-Sama** [unilock/MahouTetra#1]

**Comment by unilock** [comment]
<img width="878" alt="Screenshot 2023-09-25 at 9 18 09 PM" src="https://github.com/unilock/MahouTetra/assets/11802133/1a94d9e1-0a03-48ff-a65b-db6a9d24a9b8">

***

***

<img width="882" alt="Screenshot 2023-09-25 at 9 18 22 PM" src="https://github.com/unilock/MahouTetra/assets/11802133/5808a008-b690-463e-866d-9abffca93dcd">

***

***

<img width="888" alt="Screenshot 2023-09-25 at 9 18 35 PM" src="https://github.com/unilock/MahouTetra/assets/11802133/8f23520a-41e8-49c7-9b31-85d8f29ee9d0">
